"""Creates models

Revision ID: 438b247e904a
Revises: 
Create Date: 2023-04-27 10:19:09.586099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438b247e904a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants'))
    )
    op.create_table('swipe_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_swipe_sessions')),
    sa.UniqueConstraint('connection_code', name=op.f('uq_swipe_sessions_connection_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_one_id', sa.Integer(), nullable=True),
    sa.Column('friend_two_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_one_id'], ['users.id'], name=op.f('fk_friends_friend_one_id_users')),
    sa.ForeignKeyConstraint(['friend_two_id'], ['users.id'], name=op.f('fk_friends_friend_two_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friends'))
    )
    op.create_table('swipe_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('swipe_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_swipe_instances_restaurant_id_restaurants')),
    sa.ForeignKeyConstraint(['swipe_session_id'], ['swipe_sessions.id'], name=op.f('fk_swipe_instances_swipe_session_id_swipe_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_swipe_instances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_swipe_instances'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swipe_instances')
    op.drop_table('friends')
    op.drop_table('users')
    op.drop_table('swipe_sessions')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
