"""Adds 'accepted' into Friend table

Revision ID: 6c484d2d483d
Revises: 5f031451a178
Create Date: 2023-05-03 15:54:33.771070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c484d2d483d'
down_revision = '5f031451a178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###
